import type { ToolConfig } from "../types.ts";

/**
 * Headless single-prompt adapters ported from promptpipe builtins / capability matrix.
 * Interactive, shell, slash, and skill overlays are intentionally omitted for the API gateway.
 */
export const builtinTools: Record<string, ToolConfig> = {
  codex: {
    enabled: true,
    description: "OpenAI Codex CLI non-interactive exec",
    command: ["codex", "exec"],
    promptMode: "arg",
    stdinMode: "auto",
    stdinPromptArg: "-",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: ["--dangerously-bypass-approvals-and-sandbox"],
    extraArgs: [],
    aliases: [],
  },
  claude: {
    enabled: true,
    description: "Claude Code print/pipe mode",
    command: ["claude", "-p"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: ["--dangerously-skip-permissions"],
    extraArgs: [],
    aliases: ["claude-code"],
  },
  hermes: {
    enabled: true,
    description: "Hermes oneshot mode",
    command: ["hermes", "-z"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--yolo"],
    extraArgs: [],
    aliases: [],
  },
  fm: {
    enabled: true,
    description: "Apple Foundation Models respond",
    command: ["fm", "respond", "--no-stream"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  goose: {
    enabled: true,
    description: "Goose run with quiet stdout",
    command: ["goose", "run", "-q"],
    promptMode: "flag",
    promptFlag: "-t",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  copilot: {
    enabled: true,
    description: "GitHub Copilot CLI non-interactive silent mode",
    command: ["copilot"],
    promptMode: "flag",
    promptFlag: "-p",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--allow-all"],
    extraArgs: ["-s"],
    aliases: ["gh-copilot"],
  },
  cursor: {
    enabled: true,
    description: "Cursor Agent print mode",
    command: ["cursor-agent", "-p"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--force", "--trust"],
    extraArgs: [],
    aliases: ["cursor"],
  },
  opencode: {
    enabled: true,
    description: "OpenCode non-interactive run",
    command: ["opencode", "run"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--auto"],
    extraArgs: [],
    aliases: ["oc"],
  },
  devin: {
    enabled: true,
    description: "Devin CLI print mode",
    command: ["devin", "-p"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--permission-mode", "dangerous"],
    extraArgs: [],
    aliases: [],
  },
  grok: {
    enabled: true,
    description: "Grok Build single-turn mode",
    command: ["grok", "-p"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--always-approve"],
    extraArgs: [],
    aliases: [],
  },
  kiro: {
    enabled: true,
    description: "Kiro CLI non-interactive chat",
    command: ["kiro-cli-chat", "chat", "--no-interactive"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--trust-all-tools"],
    extraArgs: [],
    aliases: ["kiro"],
  },
  agy: {
    enabled: true,
    description: "Google Antigravity CLI print mode",
    command: ["agy", "-p"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: ["--dangerously-skip-permissions"],
    extraArgs: [],
    aliases: ["antigravity"],
  },
  qoder: {
    enabled: true,
    description: "Qoder CLI non-interactive print mode",
    command: ["qodercli", "-p"],
    promptMode: "arg",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--dangerously-skip-permissions"],
    extraArgs: [],
    aliases: [],
  },
  junie: {
    enabled: true,
    description: "JetBrains Junie CLI non-interactive --task",
    command: ["junie"],
    promptMode: "flag",
    promptFlag: "--task",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  aider: {
    enabled: true,
    description: "Aider one-shot --message mode",
    command: ["aider"],
    promptMode: "flag",
    promptFlag: "--message",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: ["--yes-always"],
    extraArgs: ["--no-stream"],
    aliases: [],
  },
  cline: {
    enabled: true,
    description: "Cline CLI one-shot prompt",
    command: ["cline"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: ["--auto-approve", "true"],
    extraArgs: [],
    aliases: [],
  },
  amp: {
    enabled: true,
    description: "Sourcegraph Amp execute mode",
    command: ["amp", "-x"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    trustedArgs: ["--dangerously-allow-all"],
    extraArgs: [],
    aliases: [],
  },
  droid: {
    enabled: true,
    description: "Factory Droid headless exec",
    command: ["droid", "exec"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: ["--auto", "medium"],
    extraArgs: [],
    aliases: [],
  },
  pi: {
    enabled: true,
    description: "Pi coding agent print mode",
    command: ["pi", "-p"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  crush: {
    enabled: true,
    description: "Charmbracelet Crush non-interactive run",
    command: ["crush", "run"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  mods: {
    enabled: true,
    description: "Charmbracelet Mods pipeline LLM",
    command: ["mods"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: ["--raw"],
    aliases: [],
  },
  sgpt: {
    enabled: true,
    description: "ShellGPT (sgpt) one-shot prompt",
    command: ["sgpt"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: ["shellgpt"],
  },
  aichat: {
    enabled: true,
    description: "aichat one-shot --no-stream",
    command: ["aichat"],
    promptMode: "arg",
    stdinMode: "auto",
    forcePromptChannel: false,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: ["--no-stream"],
    aliases: [],
  },
  oz: {
    enabled: true,
    description: "Oz agent run --prompt (headless)",
    command: ["oz", "agent", "run"],
    promptMode: "flag",
    promptFlag: "--prompt",
    stdinMode: "none",
    forcePromptChannel: true,
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: [],
    aliases: [],
  },
  "fast-agent": {
    enabled: true,
    description: "fast-agent go one-shot --message",
    command: ["fast-agent", "go"],
    promptMode: "flag",
    promptFlag: "--message",
    stdinMode: "none",
    forcePromptChannel: true,
    // note: fast-agent -m is message, not model; use long --model only if supported
    modelFlag: "--model",
    trustedArgs: [],
    extraArgs: ["--quiet"],
    aliases: ["fastagent"],
  },
};
