import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { builtinTools } from "./adapters/catalog.ts";
import { getXdgConfigPath } from "./config.ts";
import { isCommandAvailable } from "./util/runtime.ts";

function parseArgs(args: string[]) {
  let yes = false;
  let configPath: string | undefined;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "-y" || a === "--yes") yes = true;
    else if (a === "--config") {
      configPath = args[++i];
    }
  }
  return { yes, configPath };
}

export async function runInit(args: string[]) {
  const { yes, configPath } = parseArgs(args);
  const outPath = configPath ?? getXdgConfigPath();

  const detected: string[] = [];
  for (const [id, cfg] of Object.entries(builtinTools)) {
    const bin = cfg.command[0];
    if (!bin) continue;
    if (await isCommandAvailable(bin)) detected.push(id);
  }

  console.log(`[prompt-to-api] detected ${detected.length} tools on PATH:`);
  for (const id of detected) console.log(`  - ${id}`);

  const enableAll = yes || detected.length === 0;
  // Non-interactive scaffold: enable detected (or all if none / --yes)
  const enabled = new Set(enableAll && detected.length === 0 ? Object.keys(builtinTools) : detected);
  if (yes) {
    for (const id of Object.keys(builtinTools)) enabled.add(id);
  }

  const lines: string[] = [
    `# prompt-to-api config`,
    `# Generated by prompt-to-api init`,
    `host = "127.0.0.1"`,
    `port = 8788`,
    `trusted = true`,
    `timeout_ms = 600000`,
    `default_cwd = "~/.config/prompt-to-api/cwd"`,
    ``,
    `[concurrency]`,
    `max_global = 8`,
    `max_per_agent = 2`,
    ``,
  ];

  for (const [id, cfg] of Object.entries(builtinTools)) {
    const on = enabled.has(id);
    lines.push(`[tools.${id}]`);
    lines.push(`enabled = ${on}`);
    lines.push(`command = ${JSON.stringify(cfg.command)}`);
    lines.push(`prompt_mode = "${cfg.promptMode}"`);
    if (cfg.promptFlag) lines.push(`prompt_flag = "${cfg.promptFlag}"`);
    lines.push(`stdin_mode = "${cfg.stdinMode}"`);
    if (cfg.modelFlag) lines.push(`model_flag = "${cfg.modelFlag}"`);
    if (cfg.trustedArgs?.length) lines.push(`trusted_args = ${JSON.stringify(cfg.trustedArgs)}`);
    if (cfg.extraArgs?.length) lines.push(`extra_args = ${JSON.stringify(cfg.extraArgs)}`);
    if (cfg.aliases?.length) lines.push(`aliases = ${JSON.stringify(cfg.aliases)}`);
    lines.push(``);
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, lines.join("\n"), "utf-8");
  console.log(`[prompt-to-api] wrote ${outPath}`);
}
